# Generated by Django 5.2 on 2025-10-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='url',
        ),
    ]
