# Generated by Django 5.2 on 2025-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_paste'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='hash',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
