# Generated by Django 5.2 on 2025-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_paste_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='hash',
            field=models.CharField(max_length=10),
        ),
    ]
